/**
 * weather.ts — Shared TypeScript types for weather data.
 *
 * These mirror the `weather_measurements` table schema in Supabase exactly.
 * Any column added to the DB should also be added here.
 */

// ─── Raw row returned by Supabase ────────────────────────────────────────────

export interface WeatherRow {
  id: number;
  created_at: string;       // ISO-8601 timestamptz string
  temp: number | null;      // °C
  humidity: number | null;  // %
  rainfall: number | null;  // mm
  uv_index: number | null;  // 0-11 scale
  wind_dir: number | null;  // degrees (0-360)
  wind_speed: number | null; // km/h
  pressure: number | null;  // hPa
}

// ─── Payload for inserting a new reading ─────────────────────────────────────
// `id` and `created_at` are auto-generated by Postgres, so they are omitted.

export type WeatherInsertPayload = Omit<WeatherRow, 'id' | 'created_at'>;

// ─── Options for historical data queries ─────────────────────────────────────

export interface FetchHistoricalOptions {
  /** Number of rows per page (default: 50) */
  limit?: number;
  /** Zero-based page number for pagination (default: 0) */
  page?: number;
  /** Start of the date range filter (ISO-8601) */
  from?: string;
  /** End of the date range filter (ISO-8601) */
  to?: string;
}

// ─── Generic API response wrapper ────────────────────────────────────────────

export interface ApiResult<T> {
  data: T | null;
  error: string | null;
}
